:ems:
  :ems_nutanix:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :nutanix:
    :refresh_interval: 15.minutes
:http_proxy:
  :nutanix:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_nutanix: info
:workers:
  :worker_base:
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_nutanix: {}
